# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afafcb5c237dfb3ba681761c2e41502283c2e4fe07c1f180c8d403ab30758c0136871f807bf315fbddb54facd0a0f1327b27e2db326f42df53c22667d937fa24

test:
  secret_key_base: 4820d4a456f2bca0792b9f79c6599139850e6ae22fc66a3e5de7cefe734d4bf73e2820fdf69de0339deb0ee64f382f3e72b2e71886ec2f7cabdb3191dedbff09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
